# Generated by Django 4.2.7 on 2026-01-23 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgram',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('term_code', models.CharField(max_length=10)),
                ('enroll_status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], max_length=20)),
                ('enrollment_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(db_column='programme_code', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.programme')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to='students.student')),
            ],
            options={
                'db_table': 'student_programs',
                'ordering': ['-enrollment_date', 'student'],
                'indexes': [models.Index(fields=['student', 'term_code'], name='student_pro_student_bbc408_idx'), models.Index(fields=['programme', 'term_code'], name='student_pro_program_dfea12_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentModule',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('term_code', models.CharField(max_length=10)),
                ('enroll_status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('WITHDRAWN', 'Withdrawn')], max_length=20)),
                ('enrollment_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(db_column='module_code', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.module')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='module_enrollments', to='students.student')),
            ],
            options={
                'db_table': 'student_modules',
                'ordering': ['-enrollment_date', 'student'],
                'indexes': [models.Index(fields=['student', 'term_code'], name='student_mod_student_df6bd3_idx'), models.Index(fields=['module', 'term_code'], name='student_mod_module__4f786c_idx')],
            },
        ),
    ]
