# Generated by Django 4.2.7 on 2026-01-23 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('term_code', models.CharField(max_length=10)),
                ('raw_grade', models.CharField(max_length=20)),
                ('processed_grade', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('COMPENSATORY_PASS', 'Compensatory Pass')], max_length=20)),
                ('numeric_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recorded_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(db_column='module_code', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.module')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
            ],
            options={
                'db_table': 'student_results',
                'ordering': ['-recorded_date', 'student'],
                'indexes': [models.Index(fields=['student', 'term_code'], name='student_res_student_9aa84d_idx'), models.Index(fields=['module', 'term_code'], name='student_res_module__0c6a8b_idx')],
            },
        ),
    ]
