# Generated by Django 4.2.7 on 2026-01-23 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('module_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lecturer_name', models.CharField(blank=True, max_length=255)),
                ('lecturer_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['module_code'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('programme_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('programme_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lecturer_name', models.CharField(blank=True, max_length=255)),
                ('lecturer_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'programmes',
                'ordering': ['programme_code'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeModuleAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2')], null=True)),
                ('block', models.CharField(blank=True, max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(db_column='module_code', on_delete=django.db.models.deletion.CASCADE, related_name='programme_associations', to='courses.module')),
                ('programme', models.ForeignKey(db_column='programme_code', on_delete=django.db.models.deletion.CASCADE, related_name='module_associations', to='courses.programme')),
            ],
            options={
                'db_table': 'programme_module_associations',
                'ordering': ['programme', 'semester', 'module'],
                'unique_together': {('programme', 'module')},
            },
        ),
    ]
