# Generated by Django 4.2.7 on 2026-03-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='description',
        ),
        migrations.RemoveField(
            model_name='programmemoduleassociation',
            name='is_required',
        ),
    ]
